#config/constants.yml
development:
    google_client_id:            '904291423134-kgkglhfmvetflo32ns1phk9fd55gsfvo.apps.googleusercontent.com'
    google_client_secret:           'fgzHd_4rZ0jQjjEOW5pvZ4RM'
    google_client_scope:        'https://www.googleapis.com/auth/drive https://spreadsheets.google.com/feeds/'
    google_verify_redirect_uri:     'urn:ietf:wg:oauth:2.0:oob'

production:
    google_client_id:            '904291423134-kgkglhfmvetflo32ns1phk9fd55gsfvo.apps.googleusercontent.com'
    google_client_secret:           'fgzHd_4rZ0jQjjEOW5pvZ4RM'
    google_client_scope:        'https://www.googleapis.com/auth/drive https://spreadsheets.google.com/feeds/'
    google_verify_redirect_uri:     'urn:ietf:wg:oauth:2.0:oob'